In [2]:
import pygame
import time
import sys
import numpy as np

pygame 2.1.2 (SDL 2.0.18, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [61]:
display_width = 400
display_height  = 400
square_size = 20
black = ((0,0,0))

def screen(display_width, display_height):
    """sets up the display window"""
    pygame.init()
    display = pygame.display.set_mode((display_width,display_height))
    pygame.display.update()
    pygame.display.set_caption('Chess') # sets the caption on the surface (window) that opens 
    clock = pygame.time.Clock() 
    
    while True:
        
        # grid
        grid = np.indices((8,8)) + 1
        
        for x in range(8):
            for y in range(8):
                square_size = display_width/8
                rect = pygame.Rect(x*square_size, y*square_size, square_size, square_size)
                for i in range(9-1):
                    r0 = rect[i]
                
                pygame.draw.rect(display, (255,255,255), rect, 1)
                
                    
                    
#         column = x*square_size #// (square_size + margin)
#         row = y*square_size #1 // (square_size + margin)
#         for x in range(8):
#             for y in range(8):
#                 column = x*square_size #// (square_size + margin)
#                 row = y*square_size
                
#                 color = ((255,0,0))
#                 pygame.draw.rect(display,color,[(width)*x,(height)*y,width,height])

        
        
        
                
# #         yaxis = grid1[0][0][0] (upside down), xaxis = grid1[1][0][0]
# #         grid1[0][x/y][0] - keep final[0] as 0       
#     elif event.type == pygame.MOUSEBUTTONDOWN:
#             pos = pygame.mouse.get_pos()
#             column = pos[0] // (width + margin)
#             row = pos[1] // (height + margin)
#             grid[row][column] = 1
#             grid[row+1][column+1] = 1
#             grid[row-1][column-1] = 1
#             grid[row-1][column] = 1
#             grid[row+1][column] = 1
#             grid[row][column+1] = 1
#             grid[row][column-1] = 1
#             grid[row-1][column+1] = 1
#             grid[row+1][column-1] = 1
#             print("Click ", pos, "Grid coordinates: ", row, column)
#     # Set the screen background
#     screen.fill(BLACK)
#     for row in range(10):
#        for column in range(10):
#             color = WHITE
#             if grid[row][column] == 1:
#                 color = RED
#             pygame.draw.rect(screen,
#                              color,
#                              [(margin+width)*column+margin,
#                               (margin+height)*row+margin,
#                               width,
#                               height])


            
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
        pygame.display.update()

    
   
screen(display_width, display_height)            

IndexError: Invalid rect Index

In [42]:
board = [['  ' for i in range(8)] for i in range(8)]
print(board)

print(board[1])

[['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  '], ['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ']]
['  ', '  ', '  ', '  ', '  ', '  ', '  ', '  ']


In [36]:
grid = []
total = 0
for row in range(8):
    grid.append([])
    for column in range(8):
        total += 1
        grid[row].append(total)
print(grid)
grid1 = np.indices((8,8)) +1
print(grid1)
grid1[0][7][0], grid1[1][0][0]

[[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30, 31, 32], [33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48], [49, 50, 51, 52, 53, 54, 55, 56], [57, 58, 59, 60, 61, 62, 63, 64]]
[[[1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]
  [4 4 4 4 4 4 4 4]
  [5 5 5 5 5 5 5 5]
  [6 6 6 6 6 6 6 6]
  [7 7 7 7 7 7 7 7]
  [8 8 8 8 8 8 8 8]]

 [[1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]]]


(8, 1)

In [48]:
BLACK    = (   0,   0,   0)
WHITE    = ( 255, 255, 255)
GREEN    = (   0, 255,   0)
RED      = ( 255,   0,   0)
width  = 20
height = 20
margin = 5
grid = []
for i in range(10):
    grid.append([])
    for column in range(10):
        grid[i].append(0) 
pygame.init()
size = [255, 255]
screen = pygame.display.set_mode(size)
done = False
clock = pygame.time.Clock()
#Main Program Loop
while done == False:
    for event in pygame.event.get(): 
        if event.type == pygame.QUIT: 
            done = True
        elif event.type == pygame.MOUSEBUTTONDOWN:
            pos = pygame.mouse.get_pos()
            column = pos[0] // (width + margin)
            row = pos[1] // (height + margin)
            grid[row][column] = 1
            grid[row+1][column+1] = 1
            grid[row-1][column-1] = 1
            grid[row-1][column] = 1
            grid[row+1][column] = 1
            grid[row][column+1] = 1
            grid[row][column-1] = 1
            grid[row-1][column+1] = 1
            grid[row+1][column-1] = 1
            print("Click ", pos, "Grid coordinates: ", row, column)
    # Set the screen background
    screen.fill(BLACK)
    for row in range(10):
       for column in range(10):
            color = WHITE
            if grid[row][column] == 1:
                color = RED
            pygame.draw.rect(screen,
                             color,
                             [(margin+width)*column+margin,
                              (margin+height)*row+margin,
                              width,
                              height])
    clock.tick(90)
    pygame.display.flip()
pygame.quit()

Click  (161, 50) Grid coordinates:  2 6
Click  (24, 79) Grid coordinates:  3 0
Click  (81, 190) Grid coordinates:  7 3


IndexError: list index out of range

In [3]:
WIDTH = 400

WIN = pygame.display.set_mode((WIDTH, WIDTH))

""" This is creating the window that we are playing on, it takes a tuple argument which is the dimensions of the window so in this case 800 x 800px
"""

pygame.display.set_caption("Chess")
WHITE = (255, 255, 255)
GREY = (128, 128, 128)
YELLOW = (204, 204, 0)
BLUE = (50, 255, 255)
BLACK = (0, 0, 0)


class Node:
    def __init__(self, row, col, width):
        self.row = row
        self.col = col
        self.x = int(row * width)
        self.y = int(col * width)
        self.colour = WHITE
        self.occupied = None

    def draw(self, WIN):
        pygame.draw.rect(WIN, self.colour, (self.x, self.y, WIDTH / 8, WIDTH / 8))

    def setup(self, WIN):
        if starting_order[(self.row, self.col)]:
            if starting_order[(self.row, self.col)] == None:
                pass
            else:
                WIN.blit(starting_order[(self.row, self.col)], (self.x, self.y))

        """
        For now it is drawing a rectangle but eventually we are going to need it
        to use blit to draw the chess pieces instead
        """


def make_grid(rows, width):
    grid = []
    gap = WIDTH // rows
    print(gap)
    for i in range(rows):
        grid.append([])
        for j in range(rows):
            node = Node(j, i, gap)
            grid[i].append(node)
            if (i+j)%2 ==1:
                grid[i][j].colour = GREY
    return grid
